/** Shared styles for Work Instruction dashboard + QC inspection sheet. */

export function getWorkInstructionStyles(t) {
  return {
    page: {
      padding: 20,
      background: t.bg,
      minHeight: 'calc(100vh - 52px)',
      color: t.text,
    },
    subtitle: {
      textAlign: 'center',
      marginBottom: 16,
    },
    subtitleTitle: {
      margin: 0,
      fontSize: 18,
      fontWeight: 800,
      color: t.brand,
      letterSpacing: '0.02em',
    },
    subtitleMeta: {
      fontSize: 12,
      color: t.textDim,
      marginTop: 4,
    },
    split: {
      display: 'grid',
      gridTemplateColumns: 'minmax(280px, 1fr) minmax(300px, 1.2fr)',
      gap: 16,
      alignItems: 'start',
    },
    card: {
      background: t.surface,
      borderRadius: 10,
      border: `1px solid ${t.border}`,
      overflow: 'hidden',
    },
    cardHdr: {
      padding: '10px 14px',
      fontWeight: 700,
      fontSize: 13,
      color: '#fff',
      background: `linear-gradient(90deg, ${t.accent}dd, ${t.accent})`,
      letterSpacing: '0.03em',
      textTransform: 'uppercase',
    },
    infoGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
    },
    infoCell: {
      borderBottom: `1px solid ${t.border}`,
      borderRight: `1px solid ${t.border}`,
      padding: '10px 12px',
    },
    infoLabel: { color: t.textDim, fontSize: 11, marginBottom: 2 },
    infoValue: { fontWeight: 700, fontSize: 15, color: t.text },
    metricRow: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      borderTop: `1px solid ${t.border}`,
    },
    metricBox: {
      textAlign: 'center',
      padding: 14,
      background: t.surface2,
    },
    metricBoxBorder: {
      borderRight: `1px solid ${t.border}`,
    },
    metricLabel: { fontSize: 11, color: t.textDim },
    metricValue: { fontSize: 26, fontWeight: 800, color: t.accent },
    metricValueAlt: { fontSize: 26, fontWeight: 800, color: t.brand },
    cardBody: { padding: 12 },
    docGrid: { display: 'grid', gap: 10 },
    docTile: {
      cursor: 'pointer',
      padding: 12,
      textAlign: 'center',
      border: `1px solid ${t.border}`,
      borderRadius: 8,
      background: t.surface2,
      transition: 'border-color 0.15s, box-shadow 0.15s',
    },
    docTileEmpty: {
      padding: 12,
      textAlign: 'center',
      color: t.textFaint,
      fontSize: 12,
      border: `1px dashed ${t.border}`,
      borderRadius: 8,
    },
    docIcon: { fontSize: 32, marginBottom: 4, lineHeight: 1 },
    docLabel: { fontWeight: 700, fontSize: 13, color: t.text },
    docMeta: { fontSize: 11, color: t.textDim, marginTop: 2 },
    docLink: { fontSize: 11, color: t.accent, marginTop: 6, fontWeight: 600 },
    footer: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '14px 16px',
      background: t.surface2,
      borderTop: `1px solid ${t.border}`,
      flexWrap: 'wrap',
      gap: 12,
    },
    statusRow: { display: 'flex', alignItems: 'center', gap: 12 },
    statusLabel: { fontWeight: 600, fontSize: 13, color: t.text },
    statusText: { fontWeight: 700, textTransform: 'capitalize' },
    breakdownBtn: {
      background: 'none',
      border: 'none',
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      color: t.accent,
      fontWeight: 600,
      fontSize: 13,
    },
    inp: {
      padding: '7px 10px',
      borderRadius: 6,
      border: `1px solid ${t.inpBorder}`,
      background: t.inp,
      color: t.text,
      fontSize: 13,
      width: '100%',
      boxSizing: 'border-box',
    },
    inpReadonly: {
      background: t.surface2,
      color: t.textMuted,
    },
    selector: {
      padding: '7px 10px',
      borderRadius: 6,
      border: `1px solid ${t.inpBorder}`,
      background: t.inp,
      color: t.text,
      fontSize: 13,
      minWidth: 180,
    },
    approvalStep: {
      border: `1px solid ${t.border}`,
      borderRadius: 8,
      padding: 12,
      background: t.surface2,
    },
    approvalStepDone: {
      border: `1px solid ${t.brand}`,
      background: `${t.brand}18`,
    },
    approvalBadge: {
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: 10,
      fontSize: 11,
      fontWeight: 700,
    },
    btnPrimary: {
      padding: '10px 22px',
      background: t.brand,
      color: '#fff',
      border: 'none',
      borderRadius: 8,
      fontSize: 14,
      fontWeight: 700,
      cursor: 'pointer',
      width: '100%',
    },
    btnSecondary: {
      padding: '8px 18px',
      background: t.surface,
      color: t.text,
      border: `1px solid ${t.border}`,
      borderRadius: 6,
      fontSize: 13,
      fontWeight: 600,
      cursor: 'pointer',
    },
    /** Collapse control — amber when open (Hide), teal when closed (Show) */
    btnHide: {
      padding: '6px 14px',
      background: '#f59e0b',
      color: '#1c1917',
      border: '1px solid #d97706',
      borderRadius: 6,
      fontSize: 12,
      fontWeight: 700,
      cursor: 'pointer',
      letterSpacing: '0.02em',
    },
    btnShow: {
      padding: '6px 14px',
      background: '#0d9488',
      color: '#fff',
      border: '1px solid #0f766e',
      borderRadius: 6,
      fontSize: 12,
      fontWeight: 700,
      cursor: 'pointer',
      letterSpacing: '0.02em',
    },
    /** Table structure actions — distinct greens / blues */
    btnAddRow: {
      padding: '6px 14px',
      background: '#059669',
      color: '#fff',
      border: '1px solid #047857',
      borderRadius: 6,
      fontSize: 12,
      fontWeight: 700,
      cursor: 'pointer',
    },
    btnAddColumn: {
      padding: '6px 14px',
      background: '#2563eb',
      color: '#fff',
      border: '1px solid #1d4ed8',
      borderRadius: 6,
      fontSize: 12,
      fontWeight: 700,
      cursor: 'pointer',
    },
    btnAccent: {
      padding: '8px 22px',
      background: t.accent,
      color: '#fff',
      border: 'none',
      borderRadius: 6,
      cursor: 'pointer',
      fontWeight: 600,
      fontSize: 13,
    },
    section: {
      marginBottom: 16,
      border: `1px solid ${t.border}`,
      borderRadius: 8,
      overflow: 'hidden',
      background: t.surface,
    },
    sectionTitle: {
      background: t.surface2,
      padding: '8px 12px',
      fontWeight: 700,
      fontSize: 12,
      color: t.accent,
      borderBottom: `1px solid ${t.border}`,
      textTransform: 'uppercase',
      letterSpacing: '0.04em',
    },
    table: {
      borderCollapse: 'collapse',
      width: '100%',
      fontSize: 12,
    },
    th: {
      border: '1px solid #b8860b',
      padding: '6px 5px',
      textAlign: 'center',
      background: t.accent,
      color: '#fff',
      fontWeight: 600,
    },
    thYellow: {
      border: '1px solid #b45309',
      padding: '6px 5px',
      textAlign: 'center',
      background: '#fbbf24',
      color: '#0f172a',
      fontWeight: 700,
      fontSize: 12,
      textShadow: 'none',
    },
    sectionTitleYellow: {
      background: '#fde047',
      padding: '8px 12px',
      fontWeight: 700,
      fontSize: 12,
      color: '#422006',
      borderBottom: '1px solid #ca8a04',
      textTransform: 'uppercase',
      letterSpacing: '0.04em',
      textShadow: 'none',
    },
    td: {
      border: `1px solid ${t.border}`,
      padding: '5px',
      textAlign: 'center',
      background: t.inp,
      color: t.text,
    },
    tdLabel: {
      background: t.surface2,
      fontWeight: 600,
      color: t.textMuted,
      textAlign: 'left',
      paddingLeft: 10,
    },
    cellOk: { background: 'rgba(34, 197, 94, 0.22)', color: t.brand },
    cellNok: { background: 'rgba(239, 68, 68, 0.22)', color: '#ef4444' },
    cellEdited: { background: 'rgba(245, 158, 11, 0.2)', color: '#d97706' },
    empty: { textAlign: 'center', padding: 40, color: t.textDim },
    error: { color: '#ef4444', textAlign: 'center', padding: 8, fontSize: 13 },
    grid4: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(180px, 1fr))',
      gap: 12,
    },
  };
}

export function statusDotStyle(color) {
  return {
    width: 44,
    height: 44,
    borderRadius: '50%',
    background: color,
    boxShadow: `0 0 12px ${color}88`,
    border: '3px solid rgba(255,255,255,0.85)',
    flexShrink: 0,
  };
}

export const MACHINE_STATUS_COLORS = {
  running: '#10b981',
  idle: '#f59e0b',
  breakdown: '#ef4444',
  setting_change: '#3b82f6',
  alarm: '#f472b6',
  offline: '#6b7280',
};
